export interface Advertisement{
    id:  number,
    adress:  string,
    ville: string,
    prix: number,
    prixBy: string,
    roomNumber: string,
    tenantType: string,
    picture: any,
    description: string,
    phoneNumber: string,
    email: string,
    creatorId: number,
    aProved : boolean,
}